### PR TITLE
Merge psh with bnepturner00

### PR DESCRIPTION
**Pull request by sempervictus**
Merge with Powershell import (#5390).
Rename upload_script_via_psh to stage_psh_env.
Add some entropy to the scrip variable names.
Perform compression checks prior to staging.
Add stager variable cleanup routine.

### CODE REVIEW

**Comment by sempervictus** [comment]
Just dawned on me that we have a problem here - we're using a shell execute command which would call cmd. We can punt the problem down the road by ensuring session type is powershell in the method, but long term we'll need a resolver or a session.powershell.execute.

I'm looking at porting your payload into a command in meterp such that interactive PSH works properly there (what @meatballs and i have is... not quite there). Once that happens, meterp should get a session.powershell.execute and we can hook a resolver here, or lower in the lib-space of meterp itself.

**Comment by benpturner** [comment]
@sempervictus Do I have to do anything with this or will this be merged?

**Comment by benpturner** [comment]
@sempervictus is there any update on this getting merged into master?

**Comment by benpturner** [comment]
@sempervictus Do you know when this might get merged to master?

**Pull request merged**
